export const recipes = {

  gain: [
    {
      title: "Smoothie Proteico de Banana e Amendoim",
      ingredients: [
        "2 bananas maduras",
        "2 colheres de pasta de amendoim",
        "1 scoop de whey protein",
        "300ml de leite integral",
        "1 colher de aveia",
      ],
      instructions: [
        "Coloque todos os ingredientes no liquidificador",
        "Bata até ficar homogêneo",
        "Sirva imediatamente",
      ],
      nutrition:
        "Rico em proteínas e carboidratos complexos, ideal para ganho de massa",
      calories: 650,
      protein: 40,
      carbs: 80,
      fats: 25,
    },
    {
      title: "Bowl de Aveia Hipercalórico",
      ingredients: [
        "1 xícara de aveia em flocos",
        "2 colheres de mel",
        "1 banana madura amassada",
        "1 scoop de whey protein",
        "1/2 xícara de iogurte grego",
        "Mix de castanhas",
      ],
      instructions: [
        "Misture a aveia com água quente",
        "Adicione mel e banana amassada",
        "Incorpore o whey protein e iogurte",
        "Finalize com castanhas",
      ],
      nutrition: "Alto valor energético com proteínas e gorduras boas",
      calories: 580,
      protein: 35,
      carbs: 65,
      fats: 28,
    },
    {
      title: "Wrap de Frango com Abacate",
      ingredients: [
        "2 tortillas integrais grandes",
        "200g de frango desfiado",
        "1 abacate maduro",
        "Queijo mussarela",
        "Alface e tomate",
      ],
      instructions: [
        "Aqueça as tortillas",
        "Distribua o frango e queijo",
        "Adicione fatias de abacate",
        "Finalize com vegetais",
      ],
      nutrition: "Combinação balanceada de proteínas e gorduras boas",
      calories: 750,
      protein: 45,
      carbs: 55,
      fats: 42,
    },
    {
      title: "Panqueca de Aveia e Clara",
      ingredients: [
        "6 claras de ovo",
        "1/2 xícara de aveia",
        "1 banana",
        "1 colher de pasta de amendoim",
      ],
      instructions: [
        "Bata as claras e aveia no liquidificador",
        "Cozinhe em frigideira antiaderente",
        "Recheie com banana e pasta de amendoim",
      ],
      nutrition: "Café da manhã rico em proteínas",
      calories: 480,
      protein: 38,
      carbs: 45,
      fats: 12,
    },
    {
      title: "Frango Assado com Batata Doce",
      ingredients: [
        "200g de peito de frango",
        "2 batatas doces médias",
        "1 colher de azeite",
        "Brócolis cozido",
      ],
      instructions: [
        "Tempere o frango com páprica e alho",
        "Asse batata doce em rodelas",
        "Grelhe o frango e sirva com brócolis",
      ],
      nutrition: "Combinação ideal pós-treino",
      calories: 720,
      protein: 55,
      carbs: 60,
      fats: 15,
    },
    {
      title: "Shake Hipercalórico de Abacate",
      ingredients: [
        "1 abacate",
        "1 scoop de whey baunilha",
        "500ml de leite integral",
        "2 colheres de mel",
      ],
      instructions: ["Bata todos os ingredientes", "Sirva com granola"],
      nutrition: "Alta densidade calórica",
      calories: 850,
      protein: 35,
      carbs: 70,
      fats: 45,
    },
    {
      title: "Bowl de Atum e Quinoa",
      ingredients: [
        "1 lata de atum em óleo",
        "1 xícara de quinoa cozida",
        "1/2 abacate",
        "Tomate cereja",
      ],
      instructions: [
        "Misture quinoa com atum escorrido",
        "Adicione abacate e tomate",
        "Regue com azeite",
      ],
      nutrition: "Ômega-3 e proteína magra",
      calories: 680,
      protein: 50,
      carbs: 55,
      fats: 30,
    },
    {
      title: "Omelete de Queijo com Batata",
      ingredients: [
        "4 ovos inteiros",
        "100g de batata cozida",
        "50g de queijo mussarela",
        "1 colher de azeite",
      ],
      instructions: [
        "Misture ovos batidos com batata",
        "Cozinhe em frigideira com azeite",
        "Adicione queijo e dobre",
      ],
      nutrition: "Proteína e carboidratos complexos",
      calories: 550,
      protein: 32,
      carbs: 35,
      fats: 28,
    },
    {
      title: "Sanduíche de Pasta de Amendoim",
      ingredients: [
        "2 fatias de pão integral",
        "3 colheres de pasta de amendoim",
        "1 banana em rodelas",
        "1 colher de mel",
      ],
      instructions: [
        "Passe pasta de amendoim no pão",
        "Adicione banana e mel",
        "Feche o sanduíche",
      ],
      nutrition: "Energia rápida pré-treino",
      calories: 600,
      protein: 25,
      carbs: 75,
      fats: 25,
    },
    {
      title: "Salmão Grelhado com Arroz Integral",
      ingredients: [
        "200g de salmão",
        "1 xícara de arroz integral",
        "Aspargos grelhados",
        "Limão siciliano",
      ],
      instructions: [
        "Tempere salmão com limão e ervas",
        "Cozinhe arroz integral",
        "Grelhe aspargos",
      ],
      nutrition: "Rico em ômega-3 e fibras",
      calories: 780,
      protein: 48,
      carbs: 65,
      fats: 35,
    },
    {
      title: "Mugcake Proteico de Chocolate",
      ingredients: [
        "1 scoop de whey chocolate",
        "1 ovo",
        "1 colher de cacau em pó",
        "1/2 colher de fermento",
      ],
      instructions: [
        "Misture todos os ingredientes",
        "Microondas por 90 segundos",
      ],
      nutrition: "Sobremesa hiperproteica",
      calories: 280,
      protein: 30,
      carbs: 15,
      fats: 10,
    },
    {
      title: "Ensopado de Carne com Lentilha",
      ingredients: [
        "300g de patinho moído",
        "1 xícara de lentilha cozida",
        "Cenoura e batata em cubos",
        "Caldo de carne",
      ],
      instructions: [
        "Refogue a carne com legumes",
        "Adicione lentilha e caldo",
        "Cozinhe por 40 minutos",
      ],
      nutrition: "Ferro e proteína de alta qualidade",
      calories: 650,
      protein: 55,
      carbs: 50,
      fats: 20,
    },
    {
      title: "Smoothie Pré-Treino Energético",
      ingredients: [
        "1 xícara de aveia",
        "1 scoop de whey",
        "1 banana congelada",
        "300ml de água de coco",
      ],
      instructions: [
        "Bata todos os ingredientes",
        "Sirva 30min antes do treino",
      ],
      nutrition: "Combustível para treinos intensos",
      calories: 500,
      protein: 35,
      carbs: 75,
      fats: 8,
    },
    {
      title: "Arroz Integral com Feijão e Carne Moída",
      ingredients: [
        "200g de arroz integral cozido",
        "150g de feijão carioca",
        "150g de carne moída magra",
        "1 colher de azeite",
      ],
      instructions: [
        "Cozinhe o arroz e o feijão separadamente",
        "Refogue a carne moída com temperos",
        "Misture todos os componentes",
      ],
      nutrition: "Combinação clássica brasileira hiperproteica",
      calories: 750,
      protein: 45,
      carbs: 85,
      fats: 20,
    },
    {
      title: "Vitamina de Cacau com Amêndoas",
      ingredients: [
        "500ml de leite integral",
        "2 colheres de cacau em pó",
        "1 banana",
        "30g de amêndoas",
      ],
      instructions: [
        "Bata todos os ingredientes no liquidificador",
        "Sirva com gelo",
      ],
      nutrition: "Alto teor de antioxidantes e gorduras boas",
      calories: 620,
      protein: 25,
      carbs: 55,
      fats: 35,
    },
    {
      title: "Filé Mignon com Purê de Mandioquinha",
      ingredients: [
        "250g de filé mignon",
        "3 mandioquinhas médias",
        "2 colheres de manteiga ghee",
        "Brócolis grelhado",
      ],
      instructions: [
        "Asse o filé mignon na manteiga",
        "Cozinhe e amasse a mandioquinha",
        "Sirva com brócolis",
      ],
      nutrition: "Refeição densa em nutrientes",
      calories: 890,
      protein: 60,
      carbs: 45,
      fats: 50,
    },
    {
      title: "Panqueca de Whey e Banana",
      ingredients: [
        "2 scoops de whey protein",
        "1 banana madura",
        "3 ovos",
        "1 colher de óleo de coco",
      ],
      instructions: [
        "Misture todos os ingredientes",
        "Frite em frigideira antiaderente",
        "Sirva com mel",
      ],
      nutrition: "Café da manhã rico em BCAA",
      calories: 480,
      protein: 50,
      carbs: 35,
      fats: 18,
    },
    {
      title: "Macarrão Integral com Frango e Brócolis",
      ingredients: [
        "150g de macarrão integral",
        "200g de peito de frango desfiado",
        "1 xícara de brócolis",
        "Molho de tomate caseiro",
      ],
      instructions: [
        "Cozinhe o macarrão",
        "Refogue o frango com molho e brócolis",
        "Misture tudo",
      ],
      nutrition: "Carboidratos complexos + proteína magra",
      calories: 680,
      protein: 55,
      carbs: 75,
      fats: 12,
    },
    {
      title: "Bolo de Proteína de Chocolate",
      ingredients: [
        "3 ovos",
        "2 scoops de whey chocolate",
        "1/2 xícara de aveia",
        "1 colher de fermento",
      ],
      instructions: [
        "Bata os ovos e whey no liquidificador",
        "Adicione aveia e fermento",
        "Asse por 25min a 180°C",
      ],
      nutrition: "Sobremesa anabólica",
      calories: 320,
      protein: 40,
      carbs: 25,
      fats: 8,
    },
    {
      title: "Cuscuz com Ovos e Queijo",
      ingredients: [
        "1 xícara de cuscuz marroquino",
        "4 ovos caipiras",
        "50g de queijo coalho",
        "Tomate seco",
      ],
      instructions: [
        "Hidrate o cuscuz com água quente",
        "Frite os ovos mexidos",
        "Misture com queijo e tomate",
      ],
      nutrition: "Refeição rápida pós-treino",
      calories: 580,
      protein: 38,
      carbs: 40,
      fats: 25,
    },
    {
      title: "Salmão Teriyaki com Arroz Negro",
      ingredients: [
        "200g de salmão",
        "1 xícara de arroz negro cozido",
        "Molho teriyaki light",
        "Gergelim preto",
      ],
      instructions: [
        "Grelhe o salmão com molho teriyaki",
        "Cozinhe o arroz negro",
        "Finalize com gergelim",
      ],
      nutrition: "Ômega-3 + carboidratos de baixo IG",
      calories: 720,
      protein: 48,
      carbs: 60,
      fats: 30,
    },
    {
      title: "Escondidinho de Carne Seca",
      ingredients: [
        "150g de carne seca desfiada",
        "3 batatas doces grandes",
        "50g de queijo mussarela",
        "1 colher de manteiga",
      ],
      instructions: [
        "Cozinhe e amasse a batata doce",
        "Faça camadas: carne/queijo/batata",
        "Asse por 20min",
      ],
      nutrition: "Alto teor de sódio para retenção muscular",
      calories: 850,
      protein: 50,
      carbs: 80,
      fats: 35,
    },
    {
      title: "Shake Noturno de Caseína",
      ingredients: [
        "1 scoop de caseína",
        "1 colher de pasta de amendoim",
        "300ml de leite integral",
        "1 colher de farelo de aveia",
      ],
      instructions: [
        "Bata todos os ingredientes",
        "Consuma 30min antes de dormir",
      ],
      nutrition: "Proteína de lenta absorção",
      calories: 450,
      protein: 40,
      carbs: 30,
      fats: 20,
    },
    {
      title: "Costela Assada com Mandioca",
      ingredients: [
        "300g de costela bovina",
        "2 mandiocas médias",
        "2 colheres de azeite",
        "Pimenta defumada",
      ],
      instructions: [
        "Tempere a costela com pimenta e alho",
        "Asse por 2h a 160°C",
        "Sirva com mandioca cozida",
      ],
      nutrition: "Alto teor de creatina natural",
      calories: 920,
      protein: 58,
      carbs: 70,
      fats: 45,
    },
    {
      title: "Overnight Oats Proteico",
      ingredients: [
        "1 xícara de aveia em flocos",
        "1 scoop de whey baunilha",
        "200ml de leite de amêndoa",
        "1 colher de chia",
      ],
      instructions: [
        "Misture todos os ingredientes",
        "Deixe na geladeira por 8h",
        "Adicione frutas antes de servir",
      ],
      nutrition: "Prático para dias corridos",
      calories: 480,
      protein: 38,
      carbs: 55,
      fats: 12,
    },
    {
      title: "Peito de Peru Grelhado com Couscous",
      ingredients: [
        "200g de peito de peru",
        "1 xícara de couscous marroquino",
        "1 abobrinha grelhada",
        "Molho de iogurte natural",
      ],
      instructions: [
        "Grelhe o peru com ervas finas",
        "Prepare o couscous com água fervente",
        "Monte o prato com abobrinha e molho",
      ],
      nutrition: "Proteína magra + carboidrato de rápida absorção",
      calories: 610,
      protein: 52,
      carbs: 45,
      fats: 18,
    },
    {
      title: "Bolo de Frango com Batata Baroa",
      ingredients: [
        "300g de frango desfiado",
        "3 batatas baroas cozidas",
        "50g de queijo minas",
        "1 colher de azeite",
      ],
      instructions: [
        "Amasse as batatas e forme uma base",
        "Recheie com frango e queijo",
        "Asse por 20min a 180°C",
      ],
      nutrition: "Combinação inovadora de macros",
      calories: 680,
      protein: 48,
      carbs: 50,
      fats: 25,
    },
    {
      title: "Smoothie de Café e Manteiga de Amêndoa",
      ingredients: [
        "1 café expresso gelado",
        "2 colheres de manteiga de amêndoa",
        "1 scoop de whey café",
        "300ml de leite integral",
      ],
      instructions: ["Bata todos os ingredientes", "Sirva com cubos de gelo"],
      nutrition: "Pré-treino termogênico",
      calories: 550,
      protein: 35,
      carbs: 25,
      fats: 35,
    },
    {
      title: "Risoto de Frango com Aspargos",
      ingredients: [
        "150g de arroz arbóreo",
        "200g de peito de frango",
        "8 aspargos frescos",
        "50ml de vinho branco",
      ],
      instructions: [
        "Grelhe o frango e reserve",
        "Prepare o risoto com vinho e caldo de legumes",
        "Finalize com aspargos salteados",
      ],
      nutrition: "Refeição gourmet hipercalórica",
      calories: 790,
      protein: 55,
      carbs: 85,
      fats: 18,
    },
    {
      title: "Tigela de Carne Moída com Abóbora",
      ingredients: [
        "200g de carne moída magra",
        "1/2 abóbora cabotiá assada",
        "Queijo parmesão ralado",
        "Nozes picadas",
      ],
      instructions: [
        "Refogue a carne com temperos",
        "Preencha a abóbora com a carne",
        "Finalize com queijo e nozes",
      ],
      nutrition: "Rico em zinco e magnésio",
      calories: 730,
      protein: 50,
      carbs: 40,
      fats: 40,
    },
    {
      title: "Pão de Queijo Fit com Frango",
      ingredients: [
        "1 xícara de polvilho azedo",
        "100g de peito de frango desfiado",
        "50g de queijo minas light",
        "2 ovos",
      ],
      instructions: [
        "Misture os ingredientes até formar massa",
        "Modele bolinhas",
        "Asse por 25min a 180°C",
      ],
      nutrition: "Lanches práticos para levar",
      calories: 420,
      protein: 32,
      carbs: 35,
      fats: 15,
    },
    {
      title: "Salmão ao Molho de Maracujá",
      ingredients: [
        "200g de salmão",
        "Polpa de 2 maracujás",
        "1 colher de mel",
        "Arroz selvagem",
      ],
      instructions: [
        "Grelhe o salmão",
        "Reduza a polpa com mel para fazer molho",
        "Sirva com arroz selvagem",
      ],
      nutrition: "Combinação doce-salgado funcional",
      calories: 660,
      protein: 45,
      carbs: 60,
      fats: 28,
    },
    {
      title: "Brigadeiro de Whey com Granola",
      ingredients: [
        "1 scoop de whey chocolate",
        "2 colheres de cacau em pó",
        "1 lata de leite condensado light",
        "Granola sem açúcar",
      ],
      instructions: [
        "Misture whey, cacau e leite condensado",
        "Ferva em fogo baixo até engrossar",
        "Enrole e passe na granola",
      ],
      nutrition: "Sobremesa pós-treino",
      calories: 380,
      protein: 28,
      carbs: 45,
      fats: 12,
    },

    {
      title: "Strogonoff de Carne com Arroz Branco",
      ingredients: [
        "300g de contra-filé em tiras",
        "1 cebola picada",
        "200g de champignon",
        "1 caixa de creme de leite light",
      ],
      instructions: [
        "Refogue a carne com cebola",
        "Adicione champignon e molho",
        "Finalize com creme de leite",
      ],
      nutrition: "Clássico brasileiro adaptado",
      calories: 850,
      protein: 60,
      carbs: 45,
      fats: 40,
    },
    {
      title: "Omelete de Queijo com Bacon e Batata Doce",
      ingredients: [
        "4 ovos caipiras",
        "50g de queijo prato",
        "2 fatias de bacon",
        "1 batata doce cozida",
      ],
      instructions: [
        "Frite o bacon até crocante",
        "Misture com ovos batidos e queijo",
        "Sirva com batata doce em cubos",
      ],
      nutrition: "Café da manhã hiperproteico",
      calories: 680,
      protein: 42,
      carbs: 50,
      fats: 35,
    },
    {
      title: "Shake de Aveia e Manteiga de Amendoim",
      ingredients: [
        "2 scoops de whey baunilha",
        "3 colheres de aveia",
        "2 colheres de manteiga de amendoim",
        "400ml de leite integral",
      ],
      instructions: [
        "Bata todos os ingredientes",
        "Adicione gelo se necessário",
      ],
      nutrition: "Prático para volume muscular",
      calories: 720,
      protein: 55,
      carbs: 60,
      fats: 30,
    },
    {
      title: "Peito de Frango Recheado com Espinafre e Queijo",
      ingredients: [
        "250g de peito de frango",
        "1 xícara de espinafre refogado",
        "50g de queijo feta",
        "Fio de azeite",
      ],
      instructions: [
        "Faça um corte no frango e recheie",
        "Asse por 25min a 180°C",
        "Regue com azeite",
      ],
      nutrition: "Proteína magra com cálcio",
      calories: 480,
      protein: 58,
      carbs: 8,
      fats: 22,
    },
    {
      title: "Tapioca Recheada com Frango e Catupiry",
      ingredients: [
        "4 colheres de goma de tapioca",
        "150g de frango desfiado",
        "30g de catupiry light",
        "Tomate seco",
      ],
      instructions: [
        "Prepare a tapioca na frigideira",
        "Recheie com frango e queijo",
        "Finalize com tomate seco",
      ],
      nutrition: "Lanche rápido pré-treino",
      calories: 420,
      protein: 40,
      carbs: 35,
      fats: 15,
    },
    {
      title: "Risoto de Camarão com Aspargos",
      ingredients: [
        "200g de camarão limpo",
        "1 xícara de arroz arbóreo",
        "6 aspargos",
        "50ml de vinho branco",
      ],
      instructions: [
        "Refogue o arroz com vinho",
        "Adicione camarão e aspargos",
        "Finalize com queijo parmesão",
      ],
      nutrition: "Refeição gourmet densa",
      calories: 780,
      protein: 52,
      carbs: 75,
      fats: 25,
    },
    {
      title: "Bife à Rolê com Purê de Batata",
      ingredients: [
        "300g de alcatra",
        "100g de presunto magro",
        "3 batatas grandes",
        "2 colheres de manteiga",
      ],
      instructions: [
        "Recheie a carne com presunto",
        "Asse por 40min",
        "Sirva com purê cremoso",
      ],
      nutrition: "Alta densidade calórica",
      calories: 920,
      protein: 65,
      carbs: 60,
      fats: 45,
    },
    {
      title: "Panqueca de Banana com Canela e Mel",
      ingredients: [
        "2 bananas nanicas",
        "4 ovos",
        "2 colheres de farelo de aveia",
        "Canela em pó",
      ],
      instructions: [
        "Amasse as bananas com ovos",
        "Adicione aveia e canela",
        "Frite em frigideira quente",
      ],
      nutrition: "Café da manhã energético",
      calories: 450,
      protein: 25,
      carbs: 50,
      fats: 18,
    },
    {
      title: "Escondidinho de Carne Moída com Mandioca",
      ingredients: [
        "200g de carne moída",
        "3 mandiocas cozidas",
        "50g de queijo coalho",
        "Cebola caramelizada",
      ],
      instructions: [
        "Faça camadas: mandioca/carne/queijo",
        "Asse até gratinar",
        "Decore com cebola",
      ],
      nutrition: "Comfort food nutritiva",
      calories: 760,
      protein: 48,
      carbs: 70,
      fats: 30,
    },
    {
      title: "Wrap de Omelete com Abacate e Peito de Peru",
      ingredients: [
        "3 ovos caipiras",
        "2 fatias de peito de peru",
        "1/2 abacate",
        "1 wrap integral",
      ],
      instructions: [
        "Prepare uma omelete fina",
        "Monte o wrap com os ingredientes",
        "Enrole e corte ao meio",
      ],
      nutrition: "Prático para levar na marmita",
      calories: 580,
      protein: 40,
      carbs: 35,
      fats: 30,
    },
    {
      title: "Moqueca de Peixe com Arroz de Coco",
      ingredients: [
        "300g de badejo",
        "1 xícara de leite de coco",
        "1 pimentão vermelho",
        "1 xícara de arroz integral",
      ],
      instructions: [
        "Cozinhe o peixe no leite de coco",
        "Prepare o arroz com coco ralado",
        "Sirva com coentro",
      ],
      nutrition: "Ômega-3 + gorduras MCT",
      calories: 690,
      protein: 55,
      carbs: 50,
      fats: 35,
    },
    {
      title: "Frango Xadrez com Castanha de Caju",
      ingredients: [
        "250g de frango em cubos",
        "1/2 xícara de castanha de caju",
        "Molho shoyu light",
        "Pimentão colorido",
      ],
      instructions: [
        "Salteie o frango com legumes",
        "Adicione castanhas e molho",
        "Sirva com quinua",
      ],
      nutrition: "Proteína completa + selênio",
      calories: 720,
      protein: 58,
      carbs: 40,
      fats: 38,
    },
    {
      title: "Nhoque de Batata Doce com Molho Bolonhesa",
      ingredients: [
        "3 batatas doces grandes",
        "200g de carne moída magra",
        "Molho de tomate caseiro",
        "Queijo parmesão",
      ],
      instructions: [
        "Prepare o nhoque com batata",
        "Refogue a carne com molho",
        "Finalize com queijo",
      ],
      nutrition: "Carboidrato complexo + proteína",
      calories: 680,
      protein: 45,
      carbs: 75,
      fats: 20,
    },
    {
      title: "Smoothie de Coco com Whey e Granola",
      ingredients: [
        "1 scoop de whey sabor coco",
        "200ml de leite de coco",
        "2 colheres de granola",
        "1 colher de óleo de coco",
      ],
      instructions: ["Bata whey com leite e óleo", "Decore com granola"],
      nutrition: "Pré-treino tropical",
      calories: 550,
      protein: 35,
      carbs: 40,
      fats: 30,
    },
    {
      title: "Filé de Tilápia ao Forno com Brócolis",
      ingredients: [
        "300g de filé de tilápia",
        "1 buquê de brócolis",
        "2 colheres de azeite",
        "Limão siciliano",
      ],
      instructions: [
        "Marine o peixe no limão e azeite",
        "Asse com brócolis por 20min",
      ],
      nutrition: "Proteína magra de rápida digestão",
      calories: 420,
      protein: 50,
      carbs: 15,
      fats: 18,
    },
    {
      title: "Bolinho de Proteína de Frango com Aveia",
      ingredients: [
        "200g de frango moído",
        "1/2 xícara de aveia",
        "1 ovo",
        "Especiarias a gosto",
      ],
      instructions: [
        "Misture todos os ingredientes",
        "Forme bolinhos e asse por 25min",
      ],
      nutrition: "Snack proteico para freezer",
      calories: 380,
      protein: 45,
      carbs: 25,
      fats: 12,
    },
    {
      title: "Mousse de Abacate com Whey",
      ingredients: [
        "1 abacate médio",
        "1 scoop de whey baunilha",
        "2 colheres de cacau em pó",
        "1/2 xícara de iogurte grego",
      ],
      instructions: ["Bata todos os ingredientes", "Leve à geladeira por 2h"],
      nutrition: "Sobremesa pós-treino cremosa",
      calories: 480,
      protein: 32,
      carbs: 30,
      fats: 25,
    },
  ],

  lose: [
    {
      title: "Salada de Quinoa com Frango",
      ingredients: [
        "150g de peito de frango grelhado",
        "1/2 xícara de quinoa cozida",
        "Mix de folhas verdes",
        "Tomate cereja",
        "Azeite extra virgem",
      ],
      instructions: [
        "Cozinhe a quinoa conforme instruções da embalagem",
        "Grelhe o frango temperado com ervas",
        "Misture todos os ingredientes",
        "Tempere com azeite e limão",
      ],
      nutrition: "Baixo índice glicêmico, rica em proteínas e fibras",
      calories: 350,
      protein: 35,
      carbs: 30,
      fats: 12,
    },
    {
      title: "Bowl de Atum Light",
      ingredients: [
        "1 lata de atum em água",
        "1/2 xícara de arroz integral",
        "1 ovo cozido",
        "Pepino japonês",
        "Cenoura ralada",
      ],
      instructions: [
        "Cozinhe o arroz integral",
        "Monte a base com o arroz",
        "Adicione o atum e vegetais",
        "Finalize com ovo cortado",
      ],
      nutrition: "Rico em proteína magra e fibras",
      calories: 320,
      protein: 28,
      carbs: 35,
      fats: 10,
    },
    {
      title: "Sopa Detox de Legumes",
      ingredients: [
        "2 cenouras",
        "1 abobrinha",
        "1 cebola",
        "2 talos de salsão",
        "Brócolis",
        "Gengibre",
      ],
      instructions: [
        "Pique os legumes",
        "Refogue a cebola e gengibre",
        "Adicione os legumes e água",
        "Cozinhe por 20 minutos",
      ],
      nutrition: "Baixa caloria, rica em fibras e antioxidantes",
      calories: 150,
      protein: 5,
      carbs: 25,
      fats: 2,
    },
    {
      title: "Sanduíche de Muffin Inglês com Ovo",
      ingredients: [
        "3 claras de ovo",
        "1 colher de queijo cheddar light",
        "1 muffin inglês integral",
        "1/2 xícara de melão",
        "2 colheres de nozes",
      ],
      instructions: [
        "Cozinhe as claras em panela antiaderente",
        "Toaste o muffin",
        "Monte o sanduíche",
        "Sirva com melão e nozes",
      ],
      nutrition: "Proteína magra com carboidratos complexos",
      calories: 370,
      protein: 22,
      carbs: 35,
      fats: 10,
    },
    {
      title: "Ovos Mexidos com Abacate",
      ingredients: [
        "3 claras de ovo",
        "1/4 de abacate",
        "2 tortilhas de milho",
        "2/3 xícara de morangos",
      ],
      instructions: [
        "Mexa as claras em frigideira",
        "Aqueça tortilhas",
        "Recheie com ovos e abacate",
        "Acompanhe com morangos",
      ],
      nutrition: "Gorduras saudáveis e baixo IG",
      calories: 344,
      protein: 20,
      carbs: 28,
      fats: 12,
    },
    {
      title: "Waffles Integrais",
      ingredients: [
        "1/2 xícara de aveia",
        "1/4 xícara de farinha integral",
        "1 ovo",
        "1 colher de óleo de canola",
      ],
      instructions: [
        "Misture os ingredientes",
        "Cozinhe na máquina de waffles",
        "Sirva com frutas",
      ],
      nutrition: "Fonte de fibras e proteínas",
      calories: 261,
      protein: 8,
      carbs: 35,
      fats: 7,
    },
    {
      title: "Guacamole Light",
      ingredients: [
        "1 abacate",
        "1 tomate sem sementes",
        "Suco de limão",
        "Coentro fresco",
      ],
      instructions: [
        "Amasse o abacate",
        "Misture com tomate picado",
        "Tempere com limão e coentro",
      ],
      nutrition: "Gorduras saudáveis e antioxidantes",
      calories: 150,
      protein: 2,
      carbs: 8,
      fats: 12,
    },
    {
      title: "Salada de Quinoa com Frango Grelhado",
      ingredients: [
        "100g de frango grelhado",
        "1/2 xícara de quinoa",
        "Mix de folhas verdes",
        "Tomate cereja",
      ],
      instructions: [
        "Cozinhe a quinoa",
        "Grelhe o frango",
        "Misture todos os ingredientes",
      ],
      nutrition: "Alto teor proteico",
      calories: 280,
      protein: 25,
      carbs: 22,
      fats: 8,
    },
    {
      title: "Sopa de Abóbora com Gengibre",
      ingredients: [
        "½ abóbora Hokkaido",
        "1 cebola",
        "1 dente de alho",
        "1 colher de gengibre",
      ],
      instructions: [
        "Refogue os vegetais",
        "Cozinhe até amaciar",
        "Bata no liquidificador",
      ],
      nutrition: "Rica em fibras e vitamina A",
      calories: 120,
      protein: 3,
      carbs: 20,
      fats: 2,
    },
    {
      title: "Hambúrguer de Lentilha",
      ingredients: [
        "1 xícara de lentilha cozida",
        "1/2 xícara de aveia",
        "1 cebola",
        "Temperos a gosto",
      ],
      instructions: [
        "Triture a lentilha",
        "Misture com aveia e temperos",
        "Forme hambúrgueres e grelhe",
      ],
      nutrition: "Proteína vegetal e baixa gordura",
      calories: 180,
      protein: 12,
      carbs: 25,
      fats: 3,
    },


    {
      title: "Smoothie Verde Detox",
      ingredients: [
        "1 maçã verde",
        "1 punhado de espinafre",
        "1 colher de chia",
        "200ml de água de coco",
      ],
      instructions: ["Bata todos os ingredientes", "Sirva gelado"],
      nutrition: "Desintoxicante e rico em fibras",
      calories: 110,
      protein: 3,
      carbs: 20,
      fats: 2,
    },
    {
      title: "Frango com Limão e Gergelim",
      ingredients: [
        "200g de peito de frango",
        "1 limão siciliano",
        "1 colher de gergelim",
        "Ervas frescas",
      ],
      instructions: [
        "Marine o frango no limão",
        "Grelhe com ervas",
        "Polvilhe gergelim",
      ],
      nutrition: "Proteína magra com antioxidantes",
      calories: 220,
      protein: 30,
      carbs: 3,
      fats: 8,
    },
    {
      title: "Salada Cítrica de Repolho",
      ingredients: [
        "2 xícaras de repolho roxo",
        "1 cenoura ralada",
        "Suco de laranja",
        "Hortelã fresca",
      ],
      instructions: [
        "Corte o repolho finamente",
        "Misture com cenoura",
        "Tempere com suco cítrico",
      ],
      nutrition: "Baixa caloria e rica em vitamina C",
      calories: 80,
      protein: 2,
      carbs: 15,
      fats: 0,
    },
    {
      title: "Cookie de Aveia e Banana",
      ingredients: [
        "1 banana madura",
        "1/2 xícara de aveia",
        "1 colher de canela",
      ],
      instructions: [
        "Amasse a banana",
        "Misture com aveia e canela",
        "Asse em forno 180°C por 15min",
      ],
      nutrition: "Lanche rápido e nutritivo",
      calories: 90,
      protein: 2,
      carbs: 18,
      fats: 1,
    },
    {
      title: "Ceviche de Tilápia",
      ingredients: [
        "200g de tilápia",
        "Suco de 3 limões",
        "Cebola roxa",
        "Coentro",
      ],
      instructions: [
        "Cozinhe o peixe no suco de limão",
        "Misture com vegetais",
        "Deixe marinar por 30min",
      ],
      nutrition: "Proteína magra e refrescante",
      calories: 150,
      protein: 25,
      carbs: 5,
      fats: 3,
    },
    {
      title: "Bowl de Frutas Vermelhas",
      ingredients: [
        "1/2 xícara de morangos",
        "1/2 xícara de mirtilos",
        "1 colher de chia",
        "1 colher de iogurte grego",
      ],
      instructions: ["Misture as frutas", "Polvilhe chia", "Adicione iogurte"],
      nutrition: "Antioxidantes e fibras",
      calories: 120,
      protein: 5,
      carbs: 20,
      fats: 2,
    },
    {
      title: "Espaguete de Abobrinha",
      ingredients: [
        "1 abobrinha grande",
        "Molho de tomate natural",
        "Manjericão fresco",
      ],
      instructions: [
        "Faça tiras de abobrinha",
        "Refogue rapidamente",
        "Adicione molho",
      ],
      nutrition: "Low-carb e nutritivo",
      calories: 80,
      protein: 3,
      carbs: 10,
      fats: 2,
    },
    {
      title: "Patê de Grão-de-Bico",
      ingredients: [
        "1 xícara de grão-de-bico cozido",
        "Suco de limão",
        "Alho",
        "Tahine",
      ],
      instructions: [
        "Bata todos os ingredientes",
        "Ajuste temperos",
        "Sirva com vegetais",
      ],
      nutrition: "Fonte de proteína vegetal",
      calories: 150,
      protein: 7,
      carbs: 20,
      fats: 5,
    },
    {
      title: "Omelete de Cogumelos",
      ingredients: [
        "3 claras de ovo",
        "1 xícara de cogumelos",
        "50g de queijo cottage",
        "Espinafre",
      ],
      instructions: [
        "Refogue cogumelos",
        "Misture com ovos batidos",
        "Cozinhe em frigideira",
      ],
      nutrition: "Baixo carboidrato e rico em proteína",
      calories: 180,
      protein: 22,
      carbs: 6,
      fats: 8,
    },
    {
      title: "Salmão Grelhado com Aspargos",
      ingredients: ["150g de salmão", "8 aspargos", "1 limão", "Azeite"],
      instructions: [
        "Tempere o salmão com limão",
        "Grelhe por 5min cada lado",
        "Acompanhe com aspargos",
      ],
      nutrition: "Rico em ômega-3",
      calories: 280,
      protein: 34,
      carbs: 8,
      fats: 14,
    },


    {
      title: "Wrap Light de Peru",
      ingredients: [
        "1 tortilla integral",
        "100g de peito de peru",
        "Folhas verdes",
        "Pepino",
      ],
      instructions: [
        "Espalhe mostarda na tortilla",
        "Adicione os ingredientes",
        "Enrole e corte ao meio",
      ],
      nutrition: "Refeição rápida e leve",
      calories: 220,
      protein: 25,
      carbs: 18,
      fats: 6,
    },
    {
      title: "Salada de Espinafre e Arandos",
      ingredients: [
        "2 xícaras de espinafre",
        "1/4 xícara de arandos secos",
        "1/2 pera fatiada",
        "Molho balsâmico",
      ],
      instructions: [
        "Misture os ingredientes",
        "Regue com molho",
        "Sirva imediatamente",
      ],
      nutrition: "Rica em antioxidantes",
      calories: 130,
      protein: 3,
      carbs: 25,
      fats: 2,
    },
    {
      title: "Frango Dijon com Batatas",
      ingredients: [
        "200g de peito de frango",
        "2 colheres de mostarda Dijon",
        "3 batatas pequenas",
        "Azeite",
      ],
      instructions: [
        "Tempere o frango com mostarda",
        "Asse as batatas com azeite",
        "Grelhe o frango",
      ],
      nutrition: "Combinação balanceada",
      calories: 390,
      protein: 35,
      carbs: 40,
      fats: 10,
    },
    {
      title: "Crepe de Linhaça",
      ingredients: [
        "2 ovos",
        "1 colher de farinha de linhaça",
        "1 colher de farinha de amêndoas",
      ],
      instructions: [
        "Bata os ingredientes",
        "Cozinhe em frigideira",
        "Recheie com vegetais",
      ],
      nutrition: "Low-carb e proteico",
      calories: 150,
      protein: 12,
      carbs: 5,
      fats: 8,
    },
    {
      title: "Salada de Frango com Abacate",
      ingredients: [
        "150g de frango desfiado",
        "1/2 abacate",
        "Mix de folhas",
        "Tomate seco",
      ],
      instructions: ["Misture todos os ingredientes", "Tempere com azeite"],
      nutrition: "Gorduras saudáveis e proteína",
      calories: 300,
      protein: 28,
      carbs: 10,
      fats: 18,
    },
    {
      title: "Smoothie de Manga Proteico",
      ingredients: [
        "1/2 manga",
        "1 scoop de whey protein",
        "200ml de leite de amêndoa",
      ],
      instructions: ["Bata todos os ingredientes", "Sirva gelado"],
      nutrition: "Recuperação muscular",
      calories: 200,
      protein: 25,
      carbs: 20,
      fats: 3,
    },
    {
      title: "Bolo de Banana Fit",
      ingredients: ["3 bananas", "1 xícara de aveia", "2 ovos"],
      instructions: [
        "Amasse as bananas",
        "Misture com ovos e aveia",
        "Asse por 30min",
      ],
      nutrition: "Lanche saudável",
      calories: 180,
      protein: 6,
      carbs: 30,
      fats: 4,
    },
    {
      title: "Risoto de Quinoa",
      ingredients: ["1 xícara de quinoa", "1/2 abobrinha", "Caldo de legumes"],
      instructions: [
        "Cozinhe a quinoa no caldo",
        "Adicione abobrinha ralada",
        "Misture bem",
      ],
      nutrition: "Sem glúten e nutritivo",
      calories: 250,
      protein: 8,
      carbs: 40,
      fats: 5,
    },
    {
      title: "Salada de Grão-de-Bico",
      ingredients: [
        "1 xícara de grão-de-bico cozido",
        "Pepino",
        "Tomate cereja",
        "Azeitonas",
      ],
      instructions: ["Misture todos os ingredientes", "Tempere com limão"],
      nutrition: "Fonte de fibras e proteína",
      calories: 220,
      protein: 10,
      carbs: 30,
      fats: 6,
    },
    {
      title: "Peixe Grelhado com Brócolis",
      ingredients: [
        "200g de filé de peixe branco",
        "1 xícara de brócolis",
        "Azeite",
        "Alho",
      ],
      instructions: [
        "Tempere o peixe com alho",
        "Grelhe por 5min cada lado",
        "Cozinhe brócolis no vapor",
      ],
      nutrition: "Proteína magra e baixo teor calórico",
      calories: 250,
      protein: 35,
      carbs: 8,
      fats: 10,
    },

    {
      title: "Chá Detox de Gengibre e Canela",
      ingredients: [
        "1 colher de gengibre ralado",
        "1 pau de canela",
        "500ml de água",
        "Suco de 1 limão",
      ],
      instructions: [
        "Ferva a água com gengibre e canela",
        "Coe e adicione suco de limão",
        "Beba quente ou frio",
      ],
      nutrition: "Termogênico e desintoxicante",
      calories: 20,
      protein: 0,
      carbs: 5,
      fats: 0,
    },
    {
      title: "Salada de Frango com Abacaxi Grelhado",
      ingredients: [
        "150g de frango grelhado",
        "2 fatias de abacaxi",
        "Mix de folhas verdes",
        "Molho de iogurte natural",
      ],
      instructions: [
        "Grelhe o abacaxi por 2min",
        "Corte o frango em tiras",
        "Misture com folhas e molho",
      ],
      nutrition: "Combinação doce e salgada",
      calories: 270,
      protein: 28,
      carbs: 18,
      fats: 8,
    },
    {
      title: "Smoothie de Cacau e Abacate",
      ingredients: [
        "1/2 abacate",
        "1 colher de cacau em pó",
        "200ml de leite vegetal",
        "1 colher de chia",
      ],
      instructions: ["Bata todos os ingredientes", "Sirva com gelo"],
      nutrition: "Gorduras saudáveis e antioxidantes",
      calories: 220,
      protein: 5,
      carbs: 12,
      fats: 15,
    },
    {
      title: "Omelete de Espinafre e Queijo Feta",
      ingredients: [
        "3 claras de ovo",
        "1 punhado de espinafre",
        "30g de queijo feta",
        "Tomate cereja",
      ],
      instructions: [
        "Bata as claras",
        "Refogue o espinafre",
        "Adicione queijo e tomate",
      ],
      nutrition: "Proteína magra e cálcio",
      calories: 180,
      protein: 20,
      carbs: 4,
      fats: 9,
    },
    {
      title: "Salmão com Purê de Couve-Flor",
      ingredients: [
        "150g de salmão",
        "1 xícara de couve-flor cozida",
        "1 colher de iogurte grego",
        "Salsinha",
      ],
      instructions: [
        "Asse o salmão no forno",
        "Bata a couve-flor com iogurte",
        "Sirva com salsinha",
      ],
      nutrition: "Low-carb e rico em ômega-3",
      calories: 300,
      protein: 32,
      carbs: 10,
      fats: 16,
    },
    {
      title: "Chips de Batata Doce Assados",
      ingredients: [
        "1 batata doce média",
        "1 colher de azeite",
        "Páprica defumada",
      ],
      instructions: [
        "Corte em fatias finas",
        "Tempere com azeite e páprica",
        "Asse a 180°C por 25min",
      ],
      nutrition: "Snack crocante e nutritivo",
      calories: 120,
      protein: 2,
      carbs: 25,
      fats: 3,
    },
    {
      title: "Frango Xadrez Vegetariano",
      ingredients: [
        "150g de proteína de soja",
        "1 pimentão vermelho",
        "1 cebola",
        "Molho de soja light",
      ],
      instructions: [
        "Hidrate a proteína de soja",
        "Refogue com legumes",
        "Tempere com molho",
      ],
      nutrition: "Proteína vegetal e fibras",
      calories: 200,
      protein: 22,
      carbs: 15,
      fats: 5,
    },
    {
      title: "Cuscuz com Ovo Pochê",
      ingredients: [
        "1/2 xícara de cuscuz integral",
        "1 ovo",
        "Tomate picado",
        "Coentro",
      ],
      instructions: [
        "Prepare o cuscuz com água quente",
        "Poche o ovo em água fervente",
        "Monte o prato com tomate e coentro",
      ],
      nutrition: "Café da manhã proteico",
      calories: 250,
      protein: 14,
      carbs: 35,
      fats: 6,
    },
    {
      title: "Ratatouille de Legumes Assados",
      ingredients: [
        "1 berinjela",
        "1 abobrinha",
        "1 pimentão amarelo",
        "Molho de tomate caseiro",
      ],
      instructions: [
        "Corte os legumes em rodelas",
        "Monte camadas em assadeira",
        "Regue com molho e asse",
      ],
      nutrition: "Vegetariano e low-carb",
      calories: 150,
      protein: 4,
      carbs: 20,
      fats: 3,
    },
    {
      title: "Shake de Café e Cacau",
      ingredients: [
        "1 café expresso frio",
        "1 scoop de whey proteico",
        "200ml de leite de amêndoa",
        "Gelo",
      ],
      instructions: ["Bata todos os ingredientes", "Sirva imediatamente"],
      nutrition: "Energia sem açúcar",
      calories: 160,
      protein: 25,
      carbs: 8,
      fats: 4,
    },
    {
      title: "Salada de Lentilha e Beterraba",
      ingredients: [
        "1 xícara de lentilha cozida",
        "1 beterraba cozida",
        "Queijo de cabra light",
        "Rúcula",
      ],
      instructions: [
        "Corte a beterraba em cubos",
        "Misture com lentilha e rúcula",
        "Finalize com queijo",
      ],
      nutrition: "Rica em ferro e fibras",
      calories: 280,
      protein: 18,
      carbs: 35,
      fats: 7,
    },
    {
      title: "Tacos de Alface com Frango",
      ingredients: [
        "Folhas de alface americana",
        "150g de frango desfiado",
        "Pimentão vermelho",
        "Molho de iogurte",
      ],
      instructions: [
        "Tempere o frango com especiarias",
        "Monte os tacos com alface",
        "Regue com molho",
      ],
      nutrition: "Low-carb e refrescante",
      calories: 190,
      protein: 25,
      carbs: 8,
      fats: 6,
    },
    {
      title: "Sopa de Feijão Branco",
      ingredients: [
        "1 xícara de feijão branco",
        "1 cenoura",
        "1 talo de salsão",
        "Louro",
      ],
      instructions: [
        "Cozinhe o feijão com legumes",
        "Bata parcialmente no liquidificador",
        "Sirva com salsa",
      ],
      nutrition: "Fonte de proteína vegetal",
      calories: 180,
      protein: 12,
      carbs: 30,
      fats: 1,
    },
    {
      title: "Beringela Recheada com Quinoa",
      ingredients: [
        "1 berinjela média",
        "1/2 xícara de quinoa cozida",
        "Tomate picado",
        "Queijo cottage",
      ],
      instructions: [
        "Asse a berinjela cortada ao meio",
        "Misture quinoa com tomate e queijo",
        "Recheie e leve ao forno",
      ],
      nutrition: "Vegetariano e nutritivo",
      calories: 220,
      protein: 14,
      carbs: 25,
      fats: 7,
    },
    {
      title: "Picolé de Iogurte e Frutas",
      ingredients: [
        "1 pote de iogurte natural",
        "1/2 xícara de morangos",
        "Forminhas para picolé",
      ],
      instructions: [
        "Bata os ingredientes",
        "Despeje nas forminhas",
        "Leve ao freezer por 4h",
      ],
      nutrition: "Sobremesa light",
      calories: 80,
      protein: 6,
      carbs: 10,
      fats: 2,
    },
    {
      title: "Filé de Pescada com Ervas",
      ingredients: [
        "200g de filé de pescada",
        "Suco de limão",
        "Alecrim fresco",
        "Aspargos",
      ],
      instructions: [
        "Marine o peixe no limão e alecrim",
        "Grelhe por 4min cada lado",
        "Sirva com aspargos",
      ],
      nutrition: "Proteína magra e digestiva",
      calories: 210,
      protein: 35,
      carbs: 2,
      fats: 7,
    },
    {
      title: "Panqueca de Banana e Canela",
      ingredients: ["1 banana madura", "2 ovos", "1 colher de canela"],
      instructions: [
        "Amasse a banana",
        "Misture com ovos e canela",
        "Frite em frigideira antiaderente",
      ],
      nutrition: "Café da manhã rápido",
      calories: 160,
      protein: 8,
      carbs: 20,
      fats: 5,
    },
    {
      title: "Escondidinho de Carne Moída",
      ingredients: [
        "200g de carne moída magra",
        "1 xícara de purê de couve-flor",
        "Queijo ralado light",
      ],
      instructions: [
        "Refogue a carne com temperos",
        "Faça camadas: purê/carne/queijo",
        "Asse por 15min",
      ],
      nutrition: "Comfort food light",
      calories: 280,
      protein: 30,
      carbs: 12,
      fats: 10,
    },
    {
      title: "Salada de Grão-de-Bico Torrado",
      ingredients: [
        "1 xícara de grão-de-bico cozido",
        "1 colher de azeite",
        "Páprica defumada",
        "Folhas de rúcula",
      ],
      instructions: [
        "Asse o grão-de-bico com temperos",
        "Misture com rúcula",
        "Regue com limão",
      ],
      nutrition: "Snack crocante e proteico",
      calories: 210,
      protein: 10,
      carbs: 25,
      fats: 8,
    },
    {
      title: "Chá Verde com Gengibre",
      ingredients: [
        "1 colher de chá verde",
        "1 rodela de gengibre",
        "300ml de água",
        "Canela a gosto",
      ],
      instructions: [
        "Ferva a água com gengibre",
        "Adicione o chá verde",
        "Deixe em infusão por 5min",
      ],
      nutrition: "Termogênico e diurético",
      calories: 5,
      protein: 0,
      carbs: 1,
      fats: 0,
    },
    {
      title: "Bolinho de Frango com Aveia",
      ingredients: [
        "150g de frango moído",
        "1/2 xícara de aveia",
        "1 ovo",
        "Salsinha",
      ],
      instructions: [
        "Misture todos os ingredientes",
        "Forme bolinhos",
        "Asse por 20min",
      ],
      nutrition: "Proteína magra e fibras",
      calories: 180,
      protein: 22,
      carbs: 15,
      fats: 5,
    },
  ],
};


